export: true

options:
  max-time: 30
  docker: false

image: alpine:latest

definitions:
  images:
    - name: &golang-image
        image: golang:1.24.2-alpine

    - name: &ruby-image
        image: ruby:3.3.8-alpine

    - name: &golangci-image
        image: golangci/golangci-lint:v1.64.8-alpine

    - name: &goreleaser-image
        image: goreleaser/goreleaser:v2.8.2

  runners:
    - self-hosted: &selfhosted-runner
        runs-on:
          - 'self.hosted'
          - 'selfhosted.group'

  caches:
    # Caches downloaded modules via go mod download, etc.. in $GOMODCACHE ($GOPATH/pkg/mod).
    go-mod:
      path: /go/pkg/mod
      key:
        files: [ go.sum ]

    # Reuse in future go install / go tool runs.
    go-tools-build:
      path: ~/.cache/go-build
      key:
        files: [ go.sum ]

    # Reuse in future application builds.
    go-app-build:
      path: ~/.cache/go-build
      key:
        files: [ go.sum ]

    golangci-lint:
      path: ~/.cache/golangci-lint
      key:
        files: [ go.sum ]

  changesets:
    - includePaths: &code-backstage-changesets
      - ".gitattributes"
      - ".golangci.yaml"
      - ".goreleaser.yml"
      - "buf.gen.yaml"
      - "bitbucket-pipelines.yml"
      - "Makefile*"
      - "{ci,dockerfiles,packaging,scripts,tests}/**/*"
      - "**/*.go"
      - "go.*"

    - includePaths: &docs-changesets
      - ".vale.ini"
      - ".markdownlint.yml"
      - "docs/**/*"
      - "scripts/lint-docs"

  conditions:
    - condition: &code-backstage-condition
        changesets:
          includePaths: *code-backstage-changesets

  steps:
    - step: &prepare-version-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        name: Extract version
        script:
          - echo "BITBUCKET_PIPELINES_VARIABLES_PATH=$BITBUCKET_PIPELINES_VARIABLES_PATH"
          - echo "WEBITEL_VERSION=$(date +v%y.%-m)-nightly.$BITBUCKET_BUILD_NUMBER+sha.$BITBUCKET_COMMIT" >> $BITBUCKET_PIPELINES_VARIABLES_PATH
          - echo "WEBITEL_DEB_COMPONENT=nightly" >> $BITBUCKET_PIPELINES_VARIABLES_PATH
        output-variables: [ WEBITEL_VERSION, WEBITEL_DEB_COMPONENT ]

    - step: &prepare-dependencies-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        <<: *golang-image
        name: Download dependencies
        caches: [ go-mod ]
        script:
          - go mod download

    - step: &prepare-code-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        <<: *golang-image
        name: Generate code
        caches: [ go-mod, go-tools-build ]
        script:
          - apk add --no-cache git # Needed for buf to clone protos.
          - go generate ./...
        artifacts:
          paths:
            - gen/go/**
            - cmd/wire_gen.go

    - step: &test-compile-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        <<: *goreleaser-image
        name: Compile application
        size: 2x
        on-fail: { strategy: fail }
        caches: [ go-mod, go-app-build ]
        # Variables under the key are not interpolated (no expansion of $VAR_NAME).
        # They are treated literally, not dynamically resolved.
        # variables:
        # GORELEASER_CURRENT_TAG: $WEBITEL_VERSION
        script:
          - echo "BITBUCKET_PIPELINES_VARIABLES_PATH=$BITBUCKET_PIPELINES_VARIABLES_PATH"
          - export GORELEASER_CURRENT_TAG=$WEBITEL_VERSION
          - goreleaser release --clean --skip publish --skip validate
        artifacts:
          download: true
          paths:
            - dist/webitel-wfm-*.*

    - step: &test-linting-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        <<: *golangci-image
        name: Lint code
        size: 2x
        on-fail: { strategy: ignore }
        caches: [ go-mod, golangci-lint ]
        variables:
          GOLANGCI_LINT_CACHE: ~/.cache/golangci-lint
        script:
          - golangci-lint run --out-format=checkstyle > checkstyle-result.xml
        after-script:
          - pipe: atlassian/checkstyle-report:0.5.2

    - step: &test-unit-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        <<: *golang-image
        name: Unit testing
        size: 2x
        on-fail: { strategy: ignore }
        caches: [ go-mod, go-tools-build ]
        script:
          - mkdir -p test-reports
          - go test -short -v 2>&1 ./... | go run github.com/jstemmer/go-junit-report/v2@v2.1.0 -set-exit-code > test-reports/junit.xml

    - step: &test-gitleaks-step
        <<: *selfhosted-runner
        name: Secret scanner
        on-fail: { strategy: fail }
        script:
          - pipe: atlassian/git-secrets-scan:3.1.0

    - step: &deploy-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        script:
          - echo "Deployed!"

    - step: &deploy-development-step
        <<: *selfhosted-runner
        <<: *deploy-step
        name: Deploy (development)
        deployment: development

    - step: &deploy-testing-step
        <<: *selfhosted-runner
        <<: *deploy-step
        name: Deploy (testing)
        trigger: manual
        deployment: testing

    - step: &deploy-staging-step
        <<: *selfhosted-runner
        <<: *deploy-step
        name: Deploy (staging)
        trigger: manual
        deployment: staging

    - step: &publish-deb-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        <<: *ruby-image
        name: Publish .deb package
        trigger: manual
        deployment: acceptance
        script:
          - apk add --no-cache binutils
          - gem install deb-s3
          - >
            deb-s3 upload "dist/webitel-wfm-*.deb" --visibility nil --arch amd64 \
              --component "$WEBITEL_DEB_COMPONENT" \
              --codename "$DEB_CODENAME" \
              --access-key-id "$DEB_AWS_ACCESS_KEY_ID" \
              --secret-access-key "$DEB_AWS_SECRET_ACCESS_KEY" \
              --s3-region "$DEB_AWS_DEFAULT_REGION" \
              --bucket "$DEB_AWS_BUCKET_NAME"

    - step: &upload-deb-step
        <<: *selfhosted-runner
        <<: *code-backstage-condition
        name: Upload to Downloads
        trigger: manual
        script:
          - pipe: atlassian/bitbucket-upload-file:0.7.4
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              FILENAME: dist/webitel-wfm-*.deb

    - parallel: &test-parallel
        steps:
          - step: *test-compile-step
          - step: *test-linting-step
          - step: *test-unit-step
          - step: *test-gitleaks-step

pipelines:
  default:
    - stage:
        <<: *code-backstage-condition
        name: Prepare
        steps:
          - step: *prepare-version-step
          - step: *prepare-dependencies-step
          - step: *prepare-code-step

    - parallel: *test-parallel

  branches:
    # Code from development branch deploys to development
    # and testing environments with manual approves.
    main:
      - step:
          script:
            - echo "BITBUCKET_PIPELINES_VARIABLES_PATH=$BITBUCKET_PIPELINES_VARIABLES_PATH"

      - stage:
          <<: *code-backstage-condition
          name: Prepare
          steps:
            - step: *prepare-version-step
            - step: *prepare-dependencies-step
            - step: *prepare-code-step

      - parallel: *test-parallel
      - step: *deploy-development-step
      - step: *deploy-testing-step
      - step: *publish-deb-step

    # Release branches goes to staging environments.
    v*.*:
      - stage:
          <<: *code-backstage-condition
          name: Prepare
          steps:
            - step:
                <<: *prepare-version-step
                script:
                  - echo "WEBITEL_VERSION=$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER+sha.$BITBUCKET_COMMIT" >> $BITBUCKET_PIPELINES_VARIABLES_PATH
                  - echo "WEBITEL_DEB_COMPONENT=$BITBUCKET_BRANCH-releases" >> $BITBUCKET_PIPELINES_VARIABLES_PATH

            - step: *prepare-dependencies-step
            - step: *prepare-code-step

      - parallel: *test-parallel
      - step: *deploy-staging-step
      - parallel:
          steps:
            - step: *publish-deb-step
            - step: *upload-deb-step
