# Runs the actual backport after being triggered by the backport-trigger.yml workflow.
name: Backport (workflow)
run-name: "Backport for ${{ github.event.workflow_run.head_branch }} #${{ github.event.workflow_run.run_number }}"

on:
  workflow_run:
    workflows: ["Backport (trigger)"]
    types: [ completed ]

permissions: { contents: read }

jobs:
  backport:
    name: Backport
    uses: webitel/reusable-workflows/.github/workflows/_backport.yml@2b2ecb6df60e6e186d20d37b9fd6e1e5853c3ab4
    permissions:
      id-token: write
      actions: read
      contents: read

    # Only run this job if the triggering workflow was not skipped (and on webitel repositories)
    if: |
      github.event.workflow_run.head_repository.fork == false &&
      github.event.workflow_run.conclusion == 'success'
