# We need secrets to backport, but they're not available for actions ran by forks.
# So this workflow is used as a 'trigger', which the backport-workflow.yml will with
# via workflow_run
name: Backport (trigger)

on:
  pull_request:
    types: [ closed, labeled ]

permissions:
  id-token: write
  actions: read

jobs:
  trigger:
    name: Trigger backport
    uses: webitel/reusable-workflows/.github/workflows/_backport-trigger.yml@f09928e8ff63860f9656be12b9454fac00a52598

    # Only run this job if the PR has been merged and has a label containing "backport v"
    if: |
      github.event.workflow_run.head_repository.full_name == github.repository &&
      github.event.pull_request.merged == true &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'backport v')
