name: Development

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@abafeba0418db40ae8dd5e4f14457370e09187d2
    with:
      development-branch: main
      triggered-branch: ${{ github.ref_name }}
      build-number: ${{ github.run_number }}
      generated-code-path: ${{ vars.GENERATED_CODE_PATH }}

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-build.yml@abafeba0418db40ae8dd5e4f14457370e09187d2
    with:
      version: ${{ needs.prepare.outputs.version }}
      source: ${{ vars.PACKAGE_PATTERN }}
      generated-code: ${{ vars.GENERATED_CODE_PATH != '' }}

  deploy:
    name: Deploy
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@abafeba0418db40ae8dd5e4f14457370e09187d2
    secrets: inherit
    with:
      component: ${{ needs.prepare.outputs.component }}
      repository-environment: acceptance
