name: Development

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@main
    with:
      development-branch: main
      triggered-branch: ${{ github.ref_name }}
      build-number: ${{ github.run_number }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-checks.yml@main

  # FIXME: reusable workflows (uses: syntax) cannot access the github context
  #        from the calling workflow unless the values are explicitly passed as with inputs.
  output-vars:
    name: Prepare variables
    runs-on: [ arc-runner-set ]
    env:
      LDFLAGS: >
        -X github.com/webitel/webitel-wfm/cmd.commit=${{ github.sha }}
        -X github.com/webitel/webitel-wfm/cmd.branch="${{ github.ref_name }}"

    outputs:
      ldflags: ${{ steps.ldflags.outputs.LDFLAGS }}

    steps:
      - id: ldflags
        run: |
          echo "LDFLAGS=$LDFLAGS" >> $GITHUB_OUTPUT

  compile:
    name: Build
    needs: [ output-vars, prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-build.yml@main

    with:
      main-path: .
      binary-name: ${{ vars.SERVICE_NAME }}
      ldflags: >
        -s -w
        -X github.com/webitel/webitel-wfm/cmd.version="${{ needs.prepare.outputs.version }}-${{ needs.prepare.outputs.version-build }}"
        ${{ needs.output-vars.outputs.ldflags }}
        
      upload-artifact-pattern: |
        ${{ vars.SERVICE_NAME }}
        deploy/systemd/${{ vars.SERVICE_NAME }}.service

      version: ${{ needs.prepare.outputs.version }}
      version-build: ${{ needs.prepare.outputs.version-build }}
      prerelease: dev
      package-name: ${{ vars.SERVICE_NAME }}
      package-description: |
        Webitel workforce management service [WFM] package.

      package-contents: |
        src=${{ vars.SERVICE_NAME }} dst=/usr/local/bin/${{ vars.SERVICE_NAME }} type=file
        src=deploy/systemd/${{ vars.SERVICE_NAME }}.service dst=/etc/systemd/system/${{ vars.SERVICE_NAME }}.service type=config

  deploy:
    name: Deploy
    needs: [ prepare, compile ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@main
    secrets: inherit
    with:
      component: ${{ needs.prepare.outputs.component }}
      repository-environment: acceptance
