name: Pull request

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/golang/.github/workflows/prepare.yml@df153e7c810bf4e41019088a94e7cc6eae004c3a
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/golang/.github/workflows/checks.yml@df153e7c810bf4e41019088a94e7cc6eae004c3a
    permissions:
      contents: read
      actions: read
      security-events: write
