name: Pull request

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@46f75646f4aee1b272ede0ad34d1bd7944be22d6
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-checks.yml@46f75646f4aee1b272ede0ad34d1bd7944be22d6
    permissions:
      contents: read
      actions: read
      security-events: write