name: Workflow

on:
  push:
    branches: [ main, v*.* ]

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  workflow:
    name: Workflow
    uses: webitel/reusable-workflows/.github/workflows/go-workflow.yml@feat/organize
    permissions:
      actions: read
      contents: write
      security-events: write

    with:
      workflow-ref: feat/organize
      development-branch: ${{ github.event.repository.default_branch }}
      triggered-branch: ${{ github.ref_name }}
      build-number: ${{ github.run_number }}
      binary-name: webitel-wfm
      ldflags: >
        -s -w
        -X github.com/webitel/webitel-wfm/cmd.version=${{ needs.prepare.outputs.version }}-${{ needs.prepare.outputs.version-build }}
        -X github.com/webitel/webitel-wfm/cmd.commit=${{ github.sha }}
        -X github.com/webitel/webitel-wfm/cmd.branch=${{ github.ref_name }}
        
      package-name: webitel-wfm
      package-description: |
        Webitel workforce management service (WFM) package.
        
      package-contents: |
        src=deploy/systemd/webitel-wfm.service dst=/etc/systemd/system/webitel-wfm.service type=config
